interface BootTidalOptions {
  oscTarget?: string;
  oscPort?: number;
}

const CUSTOM_FX_PARAMS = [
  { name: "compress", type: "pF" },
  { name: "threshold", type: "pF" },
  { name: "ratio", type: "pF" },
  { name: "compAttack", type: "pF" },
  { name: "compRelease", type: "pF" },
  { name: "saturate", type: "pF" },
  { name: "drive", type: "pF" },
  { name: "loGain", type: "pF" },
  { name: "midGain", type: "pF" },
  { name: "hiGain", type: "pF" },
  { name: "loFreq", type: "pF" },
  { name: "hiFreq", type: "pF" },
  { name: "sideGain", type: "pF" },
  { name: "sideRelease", type: "pF" },
];

const SYNTHDEF_PARAMS = [
  { name: "cutoff", type: "pF" },
  { name: "resonance", type: "pF" },
  { name: "detune", type: "pF" },
  { name: "width", type: "pF" },
  { name: "click", type: "pF" },
  { name: "decay", type: "pF" },
];

export const generateBootTidal = (options?: BootTidalOptions): string => {
  const target = options?.oscTarget ?? "127.0.0.1";
  const port = options?.oscPort ?? 57120;

  if (target !== "127.0.0.1") {
    throw new Error(
      `OSC target must be 127.0.0.1 (got "${target}"). Non-loopback bindings are forbidden for security.`,
    );
  }

  const allParams = [...CUSTOM_FX_PARAMS, ...SYNTHDEF_PARAMS];
  const paramDefs = allParams
    .map((p) => `${p.name} = ${p.type} "${p.name}"`)
    .join("\n");

  return `-- BootTidal.hs — auto-generated by B-LIVE pipeline
-- OSC target: ${target}:${port} (loopback only)

:set -XOverloadedStrings
:set prompt ""

import Sound.Tidal.Context

:{
let target = superdirtTarget
      { oAddress = "${target}"
      , oPort = ${port}
      }
:}

:{
let orbits = [0..7]
    sdConfig = defaultConfig
      { cFrameTimespan = 1/20 }
:}

stream <- startStream sdConfig [(target, orbits)]

:{
let d1 = streamReplace stream 1
    d2 = streamReplace stream 2
    d3 = streamReplace stream 3
    d4 = streamReplace stream 4
    d5 = streamReplace stream 5
    d6 = streamReplace stream 6
    d7 = streamReplace stream 7
    d8 = streamReplace stream 8
    hush = streamHush stream
    solo = streamSolo stream
    unsolo = streamUnsolo stream
:}

-- Custom FX + SynthDef parameters
:{
let ${paramDefs}
:}

:set prompt "tidal> "
`;
};

export const validateGhcVersion = (version: string): boolean => {
  const parts = version.split(".").map(Number);
  if (parts.length < 2 || parts.some(isNaN)) return false;
  const [major, minor] = parts;
  return major > 9 || (major === 9 && minor >= 4);
};
